<?php 

use Application\CrudRepository\CrudRequests;
$primary_key='id_annonce';
$table_name ='laclef_annonce';
$operations = new CrudRequests();
$records = $operations->getAllDefault($table_name , $primary_key);
$data_keys = [
    'id_annonce',
    'uid',
    'libelle_annonce',
    'image_annonce_1',
    'description_annonce',
    'titre_transaction',
    'prix_annonce',
    'categorie_annonce',
    'vendeur_annonce',
    'vendeur_type',
    'date_crea_annonce',
    'etat_annonce',
    'token',
    'surfacebien',
    'nbpiece',
    'nbchambre',
    'nbsallebain',
    'nbtoilette',
    'meuble',
    'nbplace',
    'isexclu',
    'Terasse',
    'Balcon',
    'Neuf',
    'Garage',
    'Cave',
    'Handicape',
    'Montanthonoraire',
    'loyersanscharges',
    'charges',
    'montanttotal',
    'prixgarantie',
    'moisgarantie',
    'descriptiongarantie',
    'descriptionbien',
    'adressebien',
    'longitude',
    'latitude',
    'nompseudo',
    'numerotel',
    'zonebien',
    'communebien',
    'villebien',
    'ispro',
    'typebien',
    'surfaceterrain',
    'anneedubien',
    'titrevideo',
    'sizevideo',
    'formatvideo',
    'lienvideo'
];


$page_title = 'Annonces';
$table_fields = [
    'Id',
    'uid',
    'Libellé',
    'image_annonce_1',
    'description_annonce',
    'titre_transaction',
    'prix_annonce',
    'categorie_annonce',
    'vendeur_annonce',
    'vendeur_type',
    'date_crea_annonce',
    'etat_annonce',
    'token',
    'surfacebien',
    'nbpiece',
    'nbchambre',
    'nbsallebain',
    'nbtoilette',
    'meuble',
    'nbplace',
    'isexclu',
    'Terasse',
    'Balcon',
    'Neuf',
    'Garage',
    'Cave',
    'Handicape',
    'Montanthonoraire',
    'loyersanscharges',
    'charges',
    'montanttotal',
    'prixgarantie',
    'moisgarantie',
    'descriptiongarantie',
    'descriptionbien',
    'adressebien',
    'longitude',
    'latitude',
    'nompseudo',
    'numerotel',
    'zonebien',
    'communebien',
    'villebien',
    'ispro',
    'typebien',
    'surfaceterrain',
    'anneedubien',
    'titrevideo',
    'sizevideo',
    'formatvideo',
    'lienvideo'
];
$display_addBtn = false;
$displayEditBtn = false;
$deleteBtn_selector = 'btn-deleteAnnonce';
