<?php 
use Application\CrudRepository\CrudRequests;
$primary_key='id_recherche';
$table_name ='myclean_recherche';
$operations = new CrudRequests();
$records = $operations->getAllDefault($table_name , $primary_key);
$data_keys = [
    'id_recherche',
    'id_user',
    'nom_alerte',
    'type_annonce',
    'categorie_annonce',
    'nbappartement',
    'nbmaison',
    'nbparking',
    'nbbox',
    'nbloft',
    'nbatelier',
    'nbterrain',
    'nbbatiment',
    'nbimmeuble',
    'ville_bien1',
    'commune_bien1',
    'zone_bien1',
    'Libelle1',
    'ville_bien2',
    'commune_bien2',
    'zone_bien2',
    'Libelle2',
    'ville_bien3',
    'commune_bien3',
    'zone_bien3',
    'Libelle3',
    'surface_min_terrain',
    'surface_max_terrain',
    'surface_min_bien',
    'surface_max_bien',
    'nbpiece_bien',
    'nbchambre_bien',
    'budgetmin_bien',
    'budgetmax_bien',
    'date_crea_bien',
    'etat_recherche'
];
$page_title = 'Recherches';
$table_fields = [
    'Id Recherche',
    'Id User',
    'Nom Alerte',
    'Type Annonce',
    'Categorie Annonce',
    'Nb Appartement',
    'Nb Maison',
    'Nb Parking',
    'Nb Box',
    'Nb Loft',
    'Nb Atelier',
    'Nb Terrain',
    'Nb Batiment',
    'Nb Immeuble',
    'Ville Bien 1',
    'Commune Bien 1',
    'Zone Bien 1',
    'Libelle 1',
    'Ville Bien 2',
    'Commune Bien 2',
    'Zone Bien 2',
    'Libelle 2',
    'Ville Bien 3',
    'Commune Bien 3',
    'Zone Bien 3',
    'Libelle 3',
    'Surface Min Terrain',
    'Surface Max Terrain',
    'Surface Min Bien',
    'Surface Max Bien',
    'Nb Piece Bien',
    'Nb Chambre Bien',
    'Budget Min Bien',
    'Budget Max Bien',
    'Date Crea Bien',
    'Etat Recherche',
];
$display_addBtn = false;
$displayEditBtn = false;
$deleteBtn_selector = 'btn-deleteRecherche';
